import type { Article, Fixture, NewsSource, Player } from './types';

// Dữ liệu mẫu — chỉ hiển thị khi chưa cấu hình Supabase (NEXT_PUBLIC_SUPABASE_URL / ANON_KEY).
// Giúp xem trước giao diện trước khi kết nối cơ sở dữ liệu thật.

export const demoArticles: Article[] = [
  {
    id: 'demo-1',
    source_name: 'Marca',
    source_country: 'Tây Ban Nha',
    original_title: 'Real Madrid prepares for the new season',
    translated_title: 'Real Madrid chuẩn bị cho mùa giải mới',
    summary_vi:
      'Đội bóng Hoàng gia bước vào giai đoạn chuẩn bị với mục tiêu cạnh tranh mọi danh hiệu trong mùa giải tới.',
    content_vi:
      'Real Madrid đang hoàn thiện kế hoạch nhân sự và giáo án trước mùa giải mới. Đây là dữ liệu mẫu, sẽ được thay thế bằng bài viết thật sau khi kết nối Supabase và bật hệ thống lấy tin tự động.',
    image_url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1400&q=80',
    original_url: 'https://www.realmadrid.com',
    category: 'Tin mới',
    reliability: 'Uy tín',
    published_at: new Date().toISOString(),
    status: 'published',
    is_featured: true,
    is_transfer_news: false,
    author_name: null,
  },
  {
    id: 'demo-2',
    source_name: 'L’Équipe',
    source_country: 'Pháp',
    original_title: 'Transfer plans take shape',
    translated_title: 'Kế hoạch chuyển nhượng của Real Madrid dần rõ ràng',
    summary_vi: 'Ban lãnh đạo ưu tiên những vị trí cần tăng chiều sâu đội hình trong kỳ chuyển nhượng tới.',
    content_vi: 'Đây là dữ liệu mẫu để xem trước giao diện.',
    image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1000&q=80',
    original_url: 'https://www.lequipe.fr',
    category: 'Chuyển nhượng',
    reliability: 'Tin đồn',
    published_at: new Date(Date.now() - 3600_000).toISOString(),
    status: 'published',
    is_featured: false,
    is_transfer_news: true,
    author_name: null,
  },
  {
    id: 'demo-3',
    source_name: 'Kicker',
    source_country: 'Đức',
    original_title: 'Young stars impress',
    translated_title: 'Các tài năng trẻ gây ấn tượng trong buổi tập',
    summary_vi: 'Những cầu thủ trẻ nhận được đánh giá tích cực từ ban huấn luyện sau các buổi tập gần đây.',
    content_vi: 'Đây là dữ liệu mẫu để xem trước giao diện.',
    image_url: 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=1000&q=80',
    original_url: 'https://www.kicker.de',
    category: 'Đội hình',
    reliability: 'Uy tín',
    published_at: new Date(Date.now() - 7200_000).toISOString(),
    status: 'published',
    is_featured: false,
    is_transfer_news: false,
    author_name: null,
  },
];

export const demoSources: NewsSource[] = [
  { id: 's1', name: 'Marca', country: 'Tây Ban Nha', website_url: 'https://www.marca.com', rss_url: null, logo_url: null, reliability: 'Uy tín', is_active: true },
  { id: 's2', name: 'L’Équipe', country: 'Pháp', website_url: 'https://www.lequipe.fr', rss_url: null, logo_url: null, reliability: 'Uy tín', is_active: true },
  { id: 's3', name: 'Kicker', country: 'Đức', website_url: 'https://www.kicker.de', rss_url: null, logo_url: null, reliability: 'Uy tín', is_active: true },
];

export const demoFixtures: Fixture[] = [
  {
    id: 'f1',
    competition: 'La Liga',
    home_team: 'Real Madrid',
    away_team: 'Sevilla',
    home_logo_url: null,
    away_logo_url: null,
    stadium: 'Santiago Bernabéu',
    match_time: new Date(Date.now() + 86_400_000 * 3).toISOString(),
    status: 'scheduled',
    home_score: null,
    away_score: null,
  },
];

export const demoPlayers: Player[] = [
  {
    id: 'p1',
    name: 'Thibaut Courtois',
    slug: 'thibaut-courtois',
    shirt_number: 1,
    position: 'Thủ môn',
    nationality: 'Bỉ',
    image_url: null,
    date_of_birth: '1992-05-11',
    birthplace: 'Bree, Bỉ',
    height_cm: 199,
    is_active: true,
    bio: 'Thủ môn số 1 của Real Madrid và đội tuyển Bỉ, nổi tiếng với phản xạ xuất sắc và chiều cao lý tưởng.',
    youth_clubs: 'Genk | 2006 | 2009',
    career_clubs:
      'Genk | 2009 | 2011 | 60 | 0\nChelsea | 2011 | 2014 | 0 | 0\nAtlético Madrid | 2014 | 2018 | 132 | 0\nChelsea | 2018 | 2018 | 106 | 0\nReal Madrid | 2018 | nay | 220 | 0',
    national_team: 'Bỉ U19 | 2010 | 2011 | 8 | 0\nBỉ | 2011 | nay | 106 | 0',
    honors: 'UEFA Champions League | 2 | 2022, 2024\nLa Liga | 4 | 2020, 2022, 2024, 2025\nUEFA Europa League | 1 | 2018',
  },
  {
    id: 'p2',
    name: 'Jude Bellingham',
    slug: 'jude-bellingham',
    shirt_number: 5,
    position: 'Tiền vệ',
    nationality: 'Anh',
    image_url: null,
    date_of_birth: '2003-06-29',
    birthplace: 'Stourbridge, Anh',
    height_cm: 186,
    is_active: true,
    bio: 'Tiền vệ tấn công người Anh, ghi dấu ấn ngay mùa giải đầu tiên tại Real Madrid với khả năng săn bàn ấn tượng.',
    youth_clubs: 'Birmingham City | 2012 | 2019',
    career_clubs: 'Birmingham City | 2019 | 2020 | 41 | 4\nBorussia Dortmund | 2020 | 2023 | 132 | 24\nReal Madrid | 2023 | nay | 90 | 40',
    national_team: 'Anh U17 | 2019 | 2019 | 6 | 3\nAnh | 2020 | nay | 40 | 12',
    honors: 'UEFA Champions League | 1 | 2024\nLa Liga | 2 | 2024, 2025',
  },
  {
    id: 'p3',
    name: 'Kylian Mbappé',
    slug: 'kylian-mbappe',
    shirt_number: 10,
    position: 'Tiền đạo',
    nationality: 'Pháp',
    image_url: null,
    date_of_birth: '1998-12-20',
    birthplace: 'Paris, Pháp',
    height_cm: 178,
    is_active: true,
    bio: 'Một trong những chân sút hàng đầu thế giới, gia nhập Real Madrid năm 2024 sau nhiều năm chinh chiến tại PSG.',
    youth_clubs: 'AS Bondy | 2004 | 2013\nINF Clairefontaine | 2013 | 2015',
    career_clubs:
      'AS Monaco | 2015 | 2017 | 60 | 27\nParis Saint-Germain | 2017 | 2024 | 308 | 256\nReal Madrid | 2024 | nay | 55 | 44',
    national_team: 'Pháp U19 | 2016 | 2016 | 6 | 6\nPháp | 2017 | nay | 88 | 50',
    honors: 'Ligue 1 | 6 | 2018, 2019, 2020, 2022, 2023, 2024\nFIFA World Cup | 1 | 2018',
  },
];
